### ISSUE TITLE
executable file not found in $PATH

### ISSUE THREAD

**Issue by camerontucker** [mochizukikotaro/docker-nginx-rails-mysql#1]
17.03.1-ce-mac12 (17661)

docker-compose build
docker-compose up -d

ERROR: for app  Cannot start service app: oci runtime error: container_linux.go:247: starting container process caused "exec: \"puma\": executable file not found in $PATH"

**Comment by mochizukikotaro** [comment]
@camerontucker Thank you for your error report.
I fixed. 

- Remove `puma` command from docker-compose.yml
- Update README
- (Update rails version to 5.1.1)

Commit:
https://github.com/mochizukikotaro/docker-nginx-rails-mysql/commit/08863f3149e0702541ed5017cdd3cb1b790d8b7e

Thanks!
